"use client";

// Client-side PDF generation (jsPDF + autotable). Formal black & white style:
// Merna header, section structure, confidentiality footer, page numbers.

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { MernaAIAnswer } from "@/lib/ai/provider";

const MARGIN = 48;

function header(doc: jsPDF, companyName: string, title: string, subtitle: string) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(companyName.toUpperCase(), MARGIN, 40);
  doc.setDrawColor(23, 23, 23);
  doc.setLineWidth(1.2);
  doc.line(MARGIN, 48, doc.internal.pageSize.getWidth() - MARGIN, 48);
  doc.setTextColor(23, 23, 23);
  doc.setFontSize(18);
  doc.text(title, MARGIN, 76);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90);
  doc.text(subtitle, MARGIN, 92);
  return 112;
}

function footer(doc: jsPDF, companyName: string, confidentiality: string) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, h - 46, w - MARGIN, h - 46);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(130);
    doc.text(
      `${confidentiality} — Prepared for ${companyName} — Generated by Merna Control Center — ${new Date().toLocaleString("en-GB")}`,
      MARGIN,
      h - 34,
    );
    doc.text(`Page ${i} of ${pages}`, w - MARGIN, h - 34, { align: "right" });
  }
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  if (y > doc.internal.pageSize.getHeight() - 120) {
    doc.addPage();
    y = 60;
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(23, 23, 23);
  doc.text(text, MARGIN, y);
  return y + 14;
}

function paragraphs(doc: jsPDF, lines: string[], y: number, bullet = false): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(60);
  const width = doc.internal.pageSize.getWidth() - MARGIN * 2 - (bullet ? 12 : 0);
  for (const line of lines) {
    const wrapped = doc.splitTextToSize(line, width);
    const height = wrapped.length * 12 + 4;
    if (y + height > doc.internal.pageSize.getHeight() - 70) {
      doc.addPage();
      y = 60;
    }
    if (bullet) {
      doc.circle(MARGIN + 2.5, y - 2.5, 1.2, "F");
      doc.text(wrapped, MARGIN + 12, y);
    } else {
      doc.text(wrapped, MARGIN, y);
    }
    y += height;
  }
  return y + 4;
}

export function downloadAnswerPdf(answer: MernaAIAnswer, question: string, companyName: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = header(doc, companyName, "Merna AI Analysis", `${answer.scope} · ${answer.period}`);

  y = sectionTitle(doc, "Question", y);
  y = paragraphs(doc, [question], y);

  y = sectionTitle(doc, "Direct answer", y);
  y = paragraphs(doc, [answer.direct], y);

  if (answer.findings.length) {
    y = sectionTitle(doc, "Key findings", y);
    y = paragraphs(doc, answer.findings, y, true);
  }

  if (answer.evidence.length) {
    y = sectionTitle(doc, "Evidence", y);
    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Indicator", "Value", "Note"]],
      body: answer.evidence.map((e) => [e.label, e.value, e.sublabel ?? ""]),
      styles: { fontSize: 8.5, textColor: [60, 60, 60], lineColor: [230, 230, 230], lineWidth: 0.5 },
      headStyles: { fillColor: [23, 23, 23], textColor: [255, 255, 255], fontStyle: "bold" },
      theme: "grid",
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  }

  if (answer.calculations.length) {
    y = sectionTitle(doc, "Calculations & definitions", y);
    y = paragraphs(doc, answer.calculations, y, true);
  }
  if (answer.risks.length) {
    y = sectionTitle(doc, "Risks", y);
    y = paragraphs(doc, answer.risks, y, true);
  }
  if (answer.actions.length) {
    y = sectionTitle(doc, "Recommended actions", y);
    y = paragraphs(doc, answer.actions, y, true);
  }
  y = sectionTitle(doc, "Basis", y);
  paragraphs(doc, [
    `Confidence: ${answer.confidence.toLowerCase()}. Sources: ${answer.sources.join(", ") || "n/a"}.`,
    "Produced by the local deterministic Merna AI engine from live system data. Figures reconcile with the corresponding dashboards.",
  ], y);

  footer(doc, companyName, "Confidential");
  doc.save(`merna-ai-analysis-${Date.now()}.pdf`);
}

// ── Report builder PDF ──

import type { ReportDocData } from "@/lib/reports/types";
export type { ReportDocData, ReportSection } from "@/lib/reports/types";

export function downloadReportPdf(data: ReportDocData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = header(doc, data.companyName, data.title, `${data.reportType} · ${data.scope} · ${data.period}`);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Prepared for: ${data.preparedFor}`, MARGIN, y);
  y += 20;

  for (const section of data.sections) {
    y = sectionTitle(doc, section.heading, y);
    if (section.kpis?.length) {
      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        body: section.kpis,
        styles: { fontSize: 9, textColor: [40, 40, 40], lineColor: [235, 235, 235], lineWidth: 0.5 },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 200 } },
        theme: "grid",
      });
      y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14;
    }
    if (section.paragraphs?.length) y = paragraphs(doc, section.paragraphs, y);
    if (section.bullets?.length) y = paragraphs(doc, section.bullets, y, true);
    if (section.table) {
      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        head: [section.table.columns],
        body: section.table.rows.map((r) => r.map(String)),
        styles: { fontSize: 8, textColor: [60, 60, 60], lineColor: [230, 230, 230], lineWidth: 0.5 },
        headStyles: { fillColor: [23, 23, 23], textColor: [255, 255, 255], fontStyle: "bold" },
        theme: "grid",
      });
      y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
    }
  }

  footer(doc, data.companyName, data.confidentiality);
  doc.save(`${data.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`);
}
